name: Build TerraBrush
on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            # { platform: linux, arch: x86_64, os: ubuntu-22.04 },
            # { platform: windows, arch: x86_64, os: windows-latest },
            { platform: macos, arch: universal, os: macos-latest },
            # { platform: android, arch: arm64, os: ubuntu-22.04 },
            { platform: ios, arch: arm64, os: macos-latest },
            { platform: web, arch: wasm32, os: ubuntu-22.04 },
            { platform: web, arch: wasm32, os: ubuntu-22.04, nothreads: true },
          ]
        target-type: [template_debug, template_release]

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install multilib support
        if: ${{ matrix.target.platform == 'linux' && matrix.target.arch == 'x86_32' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62
          windows-compiler: ${{ matrix.target.platform == 'windows' && 'msvc' || 'mingw' }}

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.target.nothreads == true && 'nothreads_' || '' }}${{ matrix.target-type }}

      - name: Build GDExtension
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          THREADS_FLAG=""
          if [ "${{ matrix.target.nothreads }}" = "true" ]; then
            THREADS_FLAG="threads=no"
          fi
          if [ "${{ matrix.target.platform }}" = "windows" ]; then
            scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} use_mingw=no $THREADS_FLAG
          else
            scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} $THREADS_FLAG
          fi

      - name: Rename nothreads binaries
        if: ${{ matrix.target.nothreads == true }}
        shell: sh
        run: |
          cd demo/addons/terrabrush/bin
          for f in *.wasm; do
            mv "$f" "$(echo "$f" | sed 's/\.wasm$/.nothreads.wasm/')"
          done

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.target.nothreads == true && 'nothreads_' || '' }}${{ matrix.target-type }}

      - name: Windows - Delete compilation files
        if: ${{ matrix.target.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item demo/addons/terrabrush/bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terrabrush-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.target.nothreads == true && 'nothreads-' || '' }}${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/demo/addons/terrabrush/bin/**

  merge-builds:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge binaries Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: terrabrush-binaries
          pattern: terrabrush-*
          delete-merged: true

  merge-addon:
    runs-on: ubuntu-22.04
    needs: merge-builds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Download binaries artifact
        uses: actions/download-artifact@v4
        with:
          name: terrabrush-binaries
          path: demo/addons/terrabrush/bin/

      - name: Read TerraBrush version
        id: version
        shell: bash
        run: |
          VERSION=$(grep -oP '(?<=_version = ")[^"]+' src/terra_brush.h)
          echo "Found version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Prepare release folder
        shell: bash
        run: |
          mkdir demo/addons-release
          mkdir demo/addons-release/terrabrush
          mv demo/addons demo/addons-release/terrabrush

      - name: Upload addon folder
        uses: actions/upload-artifact@v4
        with:
          name: terrabrush-${{ steps.version.outputs.version }}
          path: demo/addons-release/

      - name: Remove binaries artifact
        uses: geekyeggo/delete-artifact@v5
        with:
            name: terrabrush-binaries